env:
  browser: true
  es2021: true
extends: [
  "eslint:recommended", 
  "google"
]
parserOptions:
  ecmaVersion: latest
plugins: [
  "jsdoc"
]
rules: {
  "no-redeclare": 0,
  "no-var": 0,
  "comma-dangle": [
    "error",
    "never"
  ],
  "eqeqeq": [
    "error",
    "always"
  ],
  "indent": [
    "error",
    2,
    {
      "CallExpression": {
        "arguments": 1, #this is a change from google’s indent rule definition
      },
      "FunctionDeclaration": {
        "body": 1,
        "parameters": 1, #this is a change from google’s indent rule definition
      },
      "FunctionExpression": {
        "body": 1,
        "parameters": 1, #this is a change from google’s indent rule definition
      },
      "MemberExpression": 1, #this is a change from google’s indent rule definition
      "ObjectExpression": 1,
      "SwitchCase": 1,
      "ignoredNodes": [
        "ConditionalExpression"
      ]
    }
  ],
  "key-spacing": [
    "error",
    "align": {
      "beforeColon": false,
      "afterColon": true,
      "on": "value"
    }
  ],
  "require-jsdoc": 0, #require-jsdoc is deprecated (the jsdoc plugin is used instead)
  "valid-jsdoc": 0, #valid-jsdoc is deprecated (the jsdoc plugin is used instead)
  "jsdoc/check-access": "error", # Recommended by the jsdoc plugin
  "jsdoc/check-alignment": "error", # Recommended by the jsdoc plugin
  "jsdoc/check-examples": 0,
  "jsdoc/check-indentation": "error",
  "jsdoc/check-line-alignment": "error",
  "jsdoc/check-param-names": "error", # Recommended by the jsdoc plugin
  "jsdoc/check-property-names": "error", # Recommended by the jsdoc plugin
  "jsdoc/check-syntax": "error",
  "jsdoc/check-tag-names": "error", # Recommended by the jsdoc plugin
  "jsdoc/check-types": "error", # Recommended by the jsdoc plugin
  "jsdoc/check-values": "error", # Recommended by the jsdoc plugin
  "jsdoc/empty-tags": "error", # Recommended by the jsdoc plugin
  "jsdoc/implements-on-classes": "error", # Recommended by the jsdoc plugin
  "jsdoc/informative-docs": "error",
  "jsdoc/match-description": "error",
  "jsdoc/multiline-blocks": "error", # Recommended by the jsdoc plugin
  "jsdoc/no-bad-blocks": "error",
  "jsdoc/no-blank-block-descriptions": "error",
  "jsdoc/no-defaults": "error",
  "jsdoc/no-missing-syntax": 0,
  "jsdoc/no-multi-asterisks": "error", # Recommended by the jsdoc plugin
  "jsdoc/no-restricted-syntax": 0,
  "jsdoc/no-types": 0,
  "jsdoc/no-undefined-types": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-asterisk-prefix": "error",
  "jsdoc/require-description": "error",
  "jsdoc/require-description-complete-sentence": "error",
  "jsdoc/require-example": 0,
  "jsdoc/require-file-overview": "error",
  "jsdoc/require-hyphen-before-param-description": "error",
  "jsdoc/require-jsdoc": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-param": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-param-description": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-param-name": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-param-type": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-property": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-property-description": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-property-name": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-property-type": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-returns": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-returns-check": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-returns-description": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-returns-type": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-throws": "error",
  "jsdoc/require-yields": "error", # Recommended by the jsdoc plugin
  "jsdoc/require-yields-check": "error", # Recommended by the jsdoc plugin
  "jsdoc/sort-tags": "error",
  "jsdoc/tag-lines": "error", # Recommended by the jsdoc plugin
  "jsdoc/valid-types": "error" # Recommended by the jsdoc plugin
}
